\ ***************************************
\   Application module written in 
\   stm8_eForth
\ ***************************************

\ REMOVE COMMENT ON NEXT LINE WHEN READY TO FLASH
\ TO-FLASH 

\ TIMER 1 REGISTERS
$5250 DUP CONSTANT T1-CR1 \ CONTROL REGISTER 1
1+ DUP CONSTANT T1-CR2 \ CONTROL REGISTER 2
1+ DUP CONSTANT T1-SMCR \ SLAVE MODE CONTROL REGISTER
1+ DUP CONSTANT T1-ETR \ EXTERNAL TRIGGER REGISTER
1+ DUP CONSTANT T1-IER \ INTERRUPT ENABLE REGISTER
1+ DUP CONSTANT T1-SR1 \ STATUS REGISTER 1
1+ DUP CONSTANT T1-SR2  \ STATUS REGISTER 2
1+ DUP CONSTANT T1-EGR \ EVENT GENERATION REGISTER
1+ DUP CONSTANT T1-CCMR1 \ CAPTURE/COMPARE MODE REG. 1
1+ DUP CONSTANT T1-CCMR2 \ CAPTURE/COMPARE MODE REG. 2
1+ DUP CONSTANT T1-CCMR3 \ CAPTURE/COMPARE MODE REG. 3
1+ DUP CONSTANT T1-CCMR4 \ CAPTURE/COMPARE MODE REG. 4
1+ DUP CONSTANT T1-CCER1 \ CAPTURE/COMPARE ENABLE REG. 1
1+ DUP CONSTANT T1-CCER2 \ CAPTURE/COMPARE ENABLE REG. 2
1+ DUP CONSTANT T1-CNTRH \ COUNTER HIGH
1+ DUP CONSTANT T1-CNTRL \ COUNTER LOW
1+ DUP CONSTANT T1-PSCRH \ PRESCALER HIGH
1+ DUP CONSTANT T1-PSCRL \ PRESCALER LOW
1+ DUP CONSTANT T1-ARRH  \ AUTO-RELOAD HIGH
1+ DUP CONSTANT T1-ARRL  \ AUTO-RELOAD LOW
1+ DUP CONSTANT T1-RCR \ REPETITION COUNTER
1+ DUP CONSTANT T1-CCR1H \ CAPTURE/COMPARE REG. 1 HIGH
1+ DUP CONSTANT T1-CCR1L \ CAPTURE/COMPARE REG. 1 LOW
1+ DUP CONSTANT T1-CCR2H \ CAPTURE/COMPARE REG. 2 HIGH
1+ DUP CONSTANT T1-CCR2L \ CAPTURE/COMPARE REG. 2 LOW
1+ DUP CONSTANT T1-CCR3H \ CAPTURE/COMPARE REG. 3 HIGH
1+ DUP CONSTANT T1-CCR3L \ CAPTURE/COMPARE REG. 3 LOW
1+ DUP CONSTANT T1-CCR4H \ CAPTURE/COMPARE REG. 4 HIGH
1+ DUP CONSTANT T1-CCR4L \ CAPTURE/COMPARE REG. 4 LOW
1+ DUP CONSTANT T1-BKR \ BREAK REGISTER
1+ DUP CONSTANT T1-DTR \ DEAD-TIME REGISTER
1+ DUP CONSTANT T1-OISR \ OUTPUT IDLE STATE REGISTER

\ TIMER 2 REGISTERS
$5300 DUP CONSTANT T2-CR1 \ CONTROL REGISTER 1
1+ DUP CONSTANT T2-IER  \ INTERRUPT ENABLE REGISTER
1+ DUP CONSTANT T2-SR1 \ STATUS REGISTER 1
1+ DUP CONSTANT T2-SR2 \ STATUS REGISTER 2
1+ DUP CONSTANT T2-EGR \ EVENT GENERATOR
1+ DUP CONSTANT T2-CCMR1 \ CAPTURE/COMPARE MODE CHANNEL 1
1+ DUP CONSTANT T2-CCMR2 \ CAPTURE/COMPARE MODE CHANNEL 2
1+ DUP CONSTANT T2-CCMR3 \ CAPTURE/COMPARE MODE CHANNEL 3
1+ DUP CONSTANT T2-CCER1 \ CAPTURE/COMPARE ENABLE REG. 1
1+ DUP CONSTANT T2-CCER2 \ CAPTURE/COMPARE ENABLE REG. 2
1+ DUP CONSTANT T2-CNTRH \ COUNTER HIGH
1+ DUP CONSTANT T2-CNTRL \ COUNTER LOW
1+ DUP CONSTANT T2-PSCR \ CLOCK PRESCALER
1+ DUP CONSTANT T2-ARRH \ AUTO-RELOAD PERIOD REG. HIGH
1+ DUP CONSTANT T2-ARRL \ AUTO-RELOAD PERIOD REG. LOW
1+ DUP CONSTANT T2-CCR1H \ CAPTURE/COMPARE VALUE CH. 1 HIGH
1+ DUP CONSTANT T2-CCR1L \ CAPTURE/COMPARE VALUE CH. 1 LOW
1+ DUP CONSTANT T2-CCR2H \ CAPTURE/CAMPARE VALUE CH. 2 HIGH
1+ DUP CONSTANT T2-CCR2L \ CAPTURE/COMPARE VALUE CH. 2 LOW
1+ DUP CONSTANT T2-CCR3H \ CAPTURE/COMPARE VALUE CH. 3 HIGH
1+ DUP CONSTANT T2-CCR3L \ CAPTURE/COMPARE VALUE CH. 3 LOW

: BSET ( b a -- ) \ set register bit
DUP C@ ROT 1 SWAP LSHIFT OR SWAP C! ;

: BRES ( b a -- ) \ reset register bit
DUP C@ ROT 1 SWAP LSHIFT NOT AND SWAP C! ;

: BTOGL ( b a -- ) \ toggle register bit
DUP C@ ROT 1 SWAP LSHIFT XOR SWAP C! ; 

: R16! ( n a -- ) \ set 16 bits register value
OVER 8 RSHIFT OVER C! 1+ C! ;

: PWM-PER ( fr -- u ) \ compute ARR value from frequency
 31250 64 ( fr -- fr 31250 64 ) 
 ROT ( -- 31250 64 fr )
 DUP ( --  31250 64 fr fr ) 
 2/ ( --  31250 64 fr fr/2 )
 >R ( --  31250 64 fr ) ( R: -- fr/2 ) 
 */MOD ( -- r q ) \ 31250*8/fr -> remainder and quotient
 SWAP ( -- q r ) \ remainder on top 
 R>   ( -- q r fr/2 ) \ round to nearest integer 
 /    ( -- q 0|1 ) \ 
 + ( -- u ) \ nearest integer
 ; 

